### ISSUE TITLE
make a modified version of retropie_packages.sh

### ISSUE THREAD

**Issue by swetoast** [mcobit/retrosmc#1]
since many of the update features are included in the retropie_packages.sh file it might be worthwhile including some of em in an easy update script, im willing to help out if you want

**Comment by mcobit** [comment]
Hi and thanks for offering that.
Unfortunately I do not want to do it that way. Using their scripts will install a ton of unneeded stuff.
I'd like to handpick updated binaries and scripts.

**Comment by ziermmar** [comment]
mcobit: could you update the binaries then? (specifically lr-snes9x-next which has some segfault issues with about 30% of my roms, see https://github.com/RetroPie/RetroPie-Setup/issues/946)

**Comment by mcobit** [comment]
Yes, I will update to the latest retropie 3.0 final image.
Unfortunately that emulator has still problems. No clue why, but it doesn't seem to be related to retropie, but to the version of the emulator they use.
If everything works according to plan, you can update the binaries via retropie-setup script in future releases yourself.
