### ISSUE TITLE
ALSA failures since November update...?

### ISSUE THREAD

**Issue by HakShak** [mcobit/retrosmc#12]
Been getting this since the update:

```
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4241:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4720:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM default
```

Anyone else having this issue?

**Comment by mcobit** [comment]
See here:
https://discourse.osmc.tv/t/howto-retrosmc-retrogaming-on-osmc/6671/480?u=mcobit

**Comment by HakShak** [comment]
Confirmed, this worked for me:

> The new kernel doesn't support loading of alsa drivers via modprobe. If you add dtparam=audio=on in to your config.txt sound works again in your game emulators (no need for modprobe). More details can be found in this thread: https://discourse.osmc.tv/t/new-update-and-squeezelite/10455/4
