### ISSUE TITLE
Can't run "install-retrosmc.sh"

### ISSUE THREAD

**Issue by Darkcrusade1** [mcobit/retrosmc#13]
I was able to go through all of the steps for downloading the GitHub repository, but after using 
"chmod -x install-retrosmc.sh" I was not able to run the shell. Every time I did "sudo ./install-retrosmc.sh" I was given the response of "./install-retrosmc.sh: Syntax error: newline unexpected" I have no idea what to do, pretty new to Linux.

**Comment by mcobit** [comment]
You should eun it without sudo.

**Comment by Darkcrusade1** [comment]
I got the same error without sudo as well.

**Comment by mcobit** [comment]
You need +x not -x

**Comment by mcobit** [comment]
Also try to redownload the file. Also, could we discuss such problems on the osmc forums so that more people can find and profit from it please?
