### ISSUE TITLE
Starting ES from launcher addon for Kodi interferes with bashisms in `runcommand.sh`

### ISSUE THREAD

**Issue by mruwek** [mcobit/retrosmc#14]
I was hit by an issue while trying to run OpenTyrian. Whole story is described at RetroPie/RetroPie-Setup#1166. It's probably not a bug of `retropie.sh` nor in `runcommand.sh` as everything works perfectly with `/home/osmc/RetroPie/scripts/retropie.sh` called from login shell via ssh.

When  `/home/osmc/RetroPie/scripts/retropie.sh` is called by RetroPie launcher addon `get_save_vars` from `/opt/retropie/supplementary/runcommand/runcommand.sh` produces blank `$save_emu` variable which is crucial for retrieving video modes. The line in question in `runcommand.sh` is [line 91](https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/supplementary/runcommand/runcommand.sh#L91).

I've created a test script that can be renamed to `/home/osmc/RetroPie/scripts/retropie.sh` which outputs `$save_emu` to tmpfile. I'll post it later today here, so you can easily reproduce this bug.

**Comment by mcobit** [comment]
So is this resolved with the solution found in the other ticket? That would be great.
Sorry. I don't have much coding and testing time lately :-(

**Comment by mruwek** [comment]
Yest it is. I'll also try to update OpenTyrian install script so it will install on OSMC without issue.
