### ISSUE TITLE
Rerosmc on OSMC/Jarvis

### ISSUE THREAD

**Issue by kgoerbig** [mcobit/retrosmc#15]
I installed Jarvis Alpha:
discourse.osmc.tv/t/testing-kodi-17-test-builds-for-raspberry-pi/11586

I tried running install-retrosmc.sh. I wget the install file directly from your gitub acct. Running the script with both root and osmc users from /home/osmc produce the same error.

osmc@osmc:~$ ./install-retrosmc.sh
./install-retrosmc.sh: line 5: syntax error near unexpected token `newline'
./install-retrosmc.sh: line 5:`<!DOCTYPE html>'

**Comment by mcobit** [comment]
Did you download the raw file like suggested in the forum thread?
Looks like you ended up downloading a html document.
What is the wget command you used? Wrong url?
