### ISSUE TITLE
could not install package(s)

### ISSUE THREAD

**Issue by rellik8821** [mcobit/retrosmc#16]
Hey 
i got a problem in the "Binary Installation".
it ran 10-15min then came the error "could not install package(s)"
which came during the Binary Installation.
![unbenannt](https://cloud.githubusercontent.com/assets/16765988/12454318/3b126050-bf97-11e5-9606-d46889c82282.png)

Those were the messages 5-10 were unable to locate the packages .
always with other packages
apt-get install some does not work?

Any Idea 

Log:
[rps_2016-01-20_162455.zip](https://github.com/mcobit/retrosmc/files/97826/rps_2016-01-20_162455.zip)

i fixed
with:
sudo apt-get autoremove libsdl2-dev libsdl2-2.0-0 libsdl1.2debian libsdl1.2-dev 

and than start script again.

**Comment by mcobit** [comment]
Not really an issue.
