### ISSUE TITLE
No sound through Jack 3,5mm

### ISSUE THREAD

**Issue by StHante** [mcobit/retrosmc#21]
I installed retrosmc and configured it to output sound through the headphones jack since my monitor does not have speakers. Unfortunately, I don't get any sound through the headphones jack.

**Comment by mcobit** [comment]
This is a problem if you have pulse audio installed. I don't have a solution for that right now unfortunately.

**Comment by StHante** [comment]
I double-checked: I do not have pulseaudio. I'm using a quite fresh installation of OSMC.

**Comment by gsantner** [comment]
`sudo amixer cset numid=3 1`
This will make your pi let go all audio output to the 3.5mm jack.
