### ISSUE TITLE
White screen when starting from Addon

### ISSUE THREAD

**Issue by frima18** [mcobit/retrosmc#23]
I installed OSMC (Release 2016.05-1) and installed retropie as described on https://discourse.osmc.tv/t/howto-retrosmc-retrogaming-on-osmc/6671 (I use a Raspberry 3)

When i start from the Addon it shows a white screen for few seconds and returns to the kodi menu.

**Comment by botverse** [comment]
Had similar issue running `./install-retrosmc.sh` with sudo, as installs everything under `/root/RetroPie` with `root:root` owner. I started from scratch and it installed well without sudo.

**Comment by mcobit** [comment]
There should be a warning now if you try to install with sudo.
