### ISSUE TITLE
Not starting after exiting back to kodi

### ISSUE THREAD

**Issue by havnar** [mcobit/retrosmc#24]
Running the via the programs menu works fine.
However when I quit emulationstation back to kodi I can't re-launch. it's show the splash screen and go back to kodi.
I have to reboot to start it.

**EDIT**: this seems to be caused by running the "restart emulation station" option instead of exit.
It will never restart but probably hang a process somewhere, I need to verify this.

**Comment by mcobit** [comment]
Yes, restart emulationstation will trigger the watchdog script to reload kodi but will create another instance of emulationstation in the background.
I cannot fix this without recompiling emulationstation on every install. And for compatibilityreasons, I don't want to ship my own version.
