### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by gsantner** [mcobit/retrosmc#27]
Hi, I don't see much changes in this project lately. And I can't see any word on Raspberry Pi 3, so this repo seems quite outdated. Are there any forks, or other projects like this with ongoing work?

**Comment by mcobit** [comment]
Why fix something that isn't broken?
Of course it works with the raspberry pi 3. This uses the same image and binaries than the 2.
What would you like to see as ongoing work?
Retropie is updated quite frequently. This is only a wrapper to use it on osmc. It still works and doesn't require much maintenance.
