### ISSUE TITLE
Wminput and tty

### ISSUE THREAD

**Issue by rhardih** [mcobit/retrosmc#29]
I've gone though all the installation steps and gotten to the point, where I can start up emulation station and get to the first time gamepad configuration screen.

I've followed the guide from https://github.com/RetroPie/RetroPie-Setup/wiki/Wiimotes-with-classic-controllers, and instead of inserting in `/etc/profile.d/10-emulationstation.sh`, (which doesn't exist since it's not a root install), I've added `rebootWithoutWiimotes=0 /home/pi/bin/attachwii.sh` before [line 32 of RetroPie/scripts/retropie.sh](https://github.com/mcobit/retrosmc/blob/master/scripts/retropie.sh#L32).

![Welcome](https://cloud.githubusercontent.com/assets/10035308/9140482/cf42f25c-3cee-11e5-8f91-c1fc1c57175c.png)

Then I start up and get to the "Welcome" screen of emulation station and it says "1 gamepad detected".

However, no button presses of the wii-mote is registered. Note: all buttons register just fine, if I pair and test outside of emulationstation, e.g. with [wii_remote_1.py](https://github.com/raspberrypilearning/robo-butler/blob/master/code/wii_remote_1.py).

Then I noticed that the `retropie.sh` script starts everything on virtual terminal 7.

Could this perhaps conflict with the input redirection of cwiid, resulting in the behaviour I'm seeing?

**Comment by mcobit** [comment]
Maybe it is, did you wait a bit after es started up? Input will not be available before kodi is shut down in the background. Also holt a button. Not press it briefly.

**Comment by mcobit** [comment]
There is also:
https://discourse.osmc.tv/t/howto-installing-retropie-alongside-osmc-rc-the-easy-way/1921/395?u=mcobit

Not sure if it is still active. Ask toast.
