### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by jcnventura** [mcobit/retrosmc#4]
Contrary to your previous script, this one doesn't add any sound libraries via apt-get.

As a result, I have no sound.

**Comment by mcobit** [comment]
Known bug.
Will be fixed in next version. Has nothing to do with sound libraries.
Please read this post carefully for a workaround:

https://discourse.osmc.tv/t/installing-retropie-alongside-osmc-rc-the-easy-way/1921/352?u=mcobit

**Comment by jcnventura** [comment]
Yes I can confirm that adding 

sudo modprobe snd_bcm2835

to the beginning of /home/osmc/RetroPie/scripts/retropie.sh fixed it for me
