### ISSUE TITLE
Installation freezes

### ISSUE THREAD

**Issue by DonLobster** [mcobit/retrosmc#40]
Hi,

I'm trying to install the RetrOSMC build, but it freezes at following line: Building CXX object es-app/CMakeFiles/emulationstation.dir/src/guis/GuiFastSelect.cpp.o.

Have tried 3 times now, also after updating all scripts. Any ideas?

Thanks!

**Comment by mcobit** [comment]
You run out of memory. See here:

https://discourse.osmc.tv/t/howto-retropie-and-osmc-retrosmc-retrogaming-on-osmc/6671/1299
