### ISSUE TITLE
Updating retropie

### ISSUE THREAD

**Issue by inverse** [mcobit/retrosmc#45]
First off thanks for making this awesome package. It was frustrating having to switch SDCards to go between games and osmc.

When updating retropie should it be alright to just go through the setup and update? Of course skipping the underlining apt updates as osmc's wiki points you should avoid doing this.

If you agree with this I can create a PR to improve the readme.

**Comment by mcobit** [comment]
Yes. You can update it via retropie-setup.sh.

Do not update the kernel. Any other updates should be fine.

Please refer to the thread at discourse.osmc.tv for more info. I would like to keep the discussion there instead as dublicatinh everything on github.

**Comment by inverse** [comment]
@mcobit Did you forget to link to the thread on discourse? I cannot see it. It might be worth linking to this in the readme.

**Comment by mcobit** [comment]
https://discourse.osmc.tv/t/howto-retropie-and-osmc-retrosmc-retrogaming-on-osmc/6671

First hit when searchong for retrosmc.
