### ISSUE TITLE
question : is it possible to use 1 gamepad for 2 players ?

### ISSUE THREAD

**Issue by pierrequere** [mcobit/retrosmc#47]
Hi and HNY !
All is in the title is it possible to use 1 gamepad for 2 players ? If the answer is yes, how to configure it ? Thanks for your answer @mcobit or all the retrosmc users :)

**Comment by mcobit** [comment]
Hi. This should be possible on a per emulator basis. Please refer to the retropie documentation on how to setup multiple controllers in retroarch.
