### ISSUE TITLE
OSMC update causes:  error while loading shared libraries: libboost_date_time.so.1.55.0

### ISSUE THREAD

**Issue by vleango** [mcobit/retrosmc#48]
When I try to launch retropie (either from Programs > Retrosmc Launcher, or emulationstation) I am getting this error:

```
 error while loading shared libraries: libboost_date_time.so.1.55.0
```

which then reloads osmc.

**Comment by jbrickner** [comment]
I have the same issue as above .  Happened on two PI3 units after an autoupdate of OSMC.

**Comment by vleango** [comment]
I since switched back to OSMC 10.17 which required reinstalling everything but at least brought everything back to working order

**Comment by mcobit** [comment]
Such issues are better reported at the retrosmc thread at the osmc forum.
There mire people will see it.
If there is rhis library missing, it could be a problem with a dependency of an update or with another addon you have installed. Try to manually reinstall libboost_date_time1.55 via apt.

**Comment by jbrickner** [comment]
Looks like a new version of libboost_date_time was installed during the most recent osmc update.  Retrosmc seems to still be looking for the libboost_date_time1.55 but now libboost_date_time1.6 is present.  apt won't let you install 1.55 in addition or over the top of 1.6.  Someone mentioned 'linking' files.  Not sure how to fix this issue.

**Comment by pdimens** [comment]
While I don't know much about the specifics of all of this, what I **can** say is that Retropie is not yet ported/updated to Debian Stretch. This last update of OSMC updates Kodi to 17.6 and also updates to  Debian to Stretch, which Retropie is not prepared for. I advise not updating.

**Comment by danyeaw** [comment]
I don't think libboost-date-time1.55.0.deb can be installed in Debian Stretch, libstdc++6:armhf (6.3.0-18) is installed which breaks libboost-date-time1.55.0. This is a work around that is working for me, some of the steps to download the other libboost dependencies may not be needed if you haven't run apt-get autoremove since OSMC updated.

    cd
    wget http://ftp.us.debian.org/debian/pool/main/i/icu/libicu52_52.1-8+deb8u6_armhf.deb http://ftp.us.debian.org/debian/pool/main/b/boost1.55/libboost-thread1.55.0_1.55.0+dfsg-3_armhf.deb http://ftp.us.debian.org/debian/pool/main/b/boost1.55/libboost-chrono1.55.0_1.55.0+dfsg-3_armhf.deb http://ftp.us.debian.org/debian/pool/main/b/boost1.55/libboost-locale1.55.0_1.55.0+dfsg-3_armhf.deb http://ftp.us.debian.org/debian/pool/main/b/boost1.55/libboost-system1.55.0_1.55.0+dfsg-3_armhf.deb
    sudo dpkg -i lib*armhf.deb
    cd /usr/lib/arm-linux-gnueabihf
    sudo ln -s libboost_date_time.so.1.62.0 libboost_date_time.so.1.55.0

@mcobit are you interested in putting this workaround in retrosmc if I or someone else submits a PR?

**Comment by mcobit** [comment]
Hi. Generally yes. A PR would be fine.
I am back at a raspberry tomorrow. I didn't get a chance to test anything until then.
Your solution is one that I would probably have tried, too.

So if you want to submit a PR, go ahead.

Ultimately it would be better to have retroplayer in kodi 18 but that seems some months off.

**Comment by Matheos96** [comment]
@mcobit @danyeaw I did your steps and then tried running the installation again. I'm not sure if this was supposed to work as a workaround to installing retrosmc on the new OSMC or not but that is what I thought, however, still getting the Sorry- message... Have I missed something crucial?

**Comment by danyeaw** [comment]
@Matheos96 what Sorry message? You mean the message that @vleango reported?

    error while loading shared libraries: libboost_date_time.so.1.55.0

I haven't tested a fresh install of retrosmc, I only was fixing the version I already had installed. We can try to resolve this issue for a fresh install also, but I need more details of what problems you ran in to.

**Comment by Matheos96** [comment]
@danyeaw Sorry for being unclear. the message stated 

> "Sorry - Raspbian/Debian Stretch (and newer) is not yet supported on the RPI
> 
> Distributor ID:	Raspbian
> Description:	Raspbian GNU/Linux 9.1 (stretch)
> Release:	9.1
> Codename:	stretch"

I found from what if-statement it came (system.sh) and commented it out and it is now running... Not sure if this was a good idea or not but since I ran ur workaround already I should not come up against that problem at least when it is done... Will keep u posted.

**Comment by Matheos96** [comment]
@danyeaw It's still going but the output is no longer as pretty... How long is it supposed to take? Been more than an hour

**Comment by Matheos96** [comment]
@danyeaw @mcobit Okay so the next day. The installation finished over night I guess. No idea but it is done. 
What I did:
1. Installed danyeaws tip above
2. Commented out the restriction for Stretch in the installer and forced it into install
3. Waited a whole lot...
4. Restarted, Installed the launcher addon. 
5. Now playing Mario :)

**Comment by mcobit** [comment]
Problem is that the fix will only work for already installed retropie.
If the installer needs to be patched to work with stretch, this might get ugly as they  change their scripts quite often. Need to think about how this can be bypassed without changing the installerscript...

**Comment by Matheos96** [comment]
Yea I was a bit afraid of what might happen but luckily it turned out to work for me, for now at least.. Latest OSMC

**Comment by danyeaw** [comment]
@mcobit Didn't @Matheos96 prove that the fix works for both new installs and ones that are already installed?

**Comment by Matheos96** [comment]
@mcobit @danyeaw Well yeah I guess. I have never in my life had retrosmc installed. First install yesterday. Not sure if ur steps were needed at all tho but probably.. I did them before anything else so I never came across errors

**Comment by DeusoftheWired** [comment]
@danyeaw Confirming working workaround on a RPi2 with latest OSMC stretch update and an old RetrOSMC install. Thanks a lot!

**Comment by mcobit** [comment]
@danyeaw He altered the installscript before installation.

**Comment by Matheos96** [comment]
@mcobit @danyeaw Yea it is not really pretty.. But worked. RPi 3 btw

**Comment by danyeaw** [comment]
@mcobit What if we download Retro-Pie and patch the install script from the retrosmc install script?

**Comment by mcobit** [comment]
Sure. That can be done and has been done before and I am happy that I didin't have to anymore as changes to the install broke this all the time. I'll talk to exobuzz feom RetroPie if he can make an exception for osmc.

**Comment by kkmaslowski** [comment]
AFAIK RetroPie does not support Debian 9 (stretch): https://github.com/RetroPie/RetroPie-Setup/issues/2091 yet. I reinstalled system and marked 2 packages as hold- base-files, base-files-osmc to stop update from jessie to stretch.

**Comment by danyeaw** [comment]
@mcobit have you had a chance to talk to exobuzz about this?

**Comment by mcobit** [comment]
Seems like he hasn't read my post yet.
I think this might resolve by itself sooner or later as raspbian also moved on. We might have to wait a little longer.

**Comment by joolswills** [comment]
Which post ? 

Stretch support is now in beta, so the code changes above are not needed. However - expect some stuff to not work. The code was there to disable RetroPie on Stretch while we were working on fixing various things up.

**Comment by mcobit** [comment]
@joolswillis
This one: https://discourse.osmc.tv/t/howto-retropie-and-osmc-retrosmc-retrogaming-on-osmc/6671/1360?u=mcobit

Thanks for your input. I thought so.
I think it is better if some stuff works than if nothing works. Time will cure that anyway.

Thanks again

**Comment by joolswills** [comment]
I don't actively watch/use that forum. Best to contact me via the RetroPie forum.

We intentionally disabled RetroPie on Stretch as people were installing it and reporting things broken (Binaries have only been built recently too). Quite a lot of fixes were required for Stretch. I would recommend people stick with Jessie until Stretch is finalised, but it is enabled now by default.

**Comment by alxlaxv** [comment]
Hello,
This workaround doesn't work for me.
Kodi is exiting, emulstation splashscreen is displayed 1 sec and then black screen.
After few seconds it restarts Kodi.
Any ideas?

**Comment by inverse** [comment]
https://github.com/RetroPie/RetroPie-Setup/issues/2091#issuecomment-374621296

Looks like stretch support is now supported.

**Comment by danyeaw** [comment]
I recommend we close this issue since RetroPie 4.4 now uses Debian Stretch.

**Comment by vleango** [comment]
ok, closing because it seems like the update to retro-pie is working now
