### ISSUE TITLE
Raspbian/Debian Stretch not yet supported

### ISSUE THREAD

**Issue by Matheos96** [mcobit/retrosmc#49]
Hello, I am getting this error, how can this be? Has OSMC moved on faster than retrosmc and changed base? This is my first time installing, latest OSMC which apperantly is on Debian Stretch 9.3...

**Comment by mcobit** [comment]
Yes. Have a look at the other thread here for a solution.

**Comment by Matheos96** [comment]
@mcobit Thanks man. I'll continue the conversation over there.
