### ISSUE TITLE
Pull request for moonlight_embedded

### ISSUE THREAD

**Issue by swetoast** [mcobit/retrosmc#5]
urgh pull requests is a pain in the ass here is my inital request anyways didnt bother with looking up how to do it proper..

Moonlight Embedded

my initial commit needs some fixing with first time setup and config but once thats done it should be a walk in the park :)

https://gitlab.com/swe_toast/retrosmc_addons/blob/master/moonlight_embedded.tar.gz

check out the files and look at the shell scripts there is room for alot of improvement in there

**Comment by mcobit** [comment]
Thanks for proposing this but I think this is not really retrogaming related so it should get it's own package.
